import React, { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { api } from "../services/api";
import { useAuth } from "../context/AuthContext.jsx";
import "./contactPortal.css";

function urgencyClass(value) { return `urgency-${String(value || "medium").toLowerCase()}`; }
export default function MyRequests() {
  const { user } = useAuth();
  const [params] = useSearchParams();
  const [trackingId, setTrackingId] = useState(params.get("tracking_id") || "");
  const [lookup, setLookup] = useState(params.get("tracking_id") || "");
  const [requests, setRequests] = useState([]); const [selected, setSelected] = useState(null); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { try { const { data } = await api.get("/contact-threads/mine", { params: trackingId ? { tracking_id: trackingId } : {} }); setRequests(data.requests || []); if (selected) { const current = await api.get(`/contact-threads/mine/${selected.id}`, { params: trackingId ? { tracking_id: trackingId } : {} }); setSelected(current.data.request); } } catch (err) { setError(err.response?.data?.error || "Could not load your requests."); } }
  useEffect(() => { load(); }, [trackingId, user?.id]);
  async function send(event) { event.preventDefault(); if (!message.trim() || !selected) return; try { const { data } = await api.post(`/contact-threads/mine/${selected.id}/messages`, { body: message }, { params: trackingId ? { tracking_id: trackingId } : {} }); setSelected(data.request); setMessage(""); load(); } catch (err) { setError(err.response?.data?.error || "Could not send your message."); } }
  return <main className="requests-page"><div className="requests-heading"><div><p className="eyebrow">Your support threads</p><h1>My requests</h1><p>Track replies from verified organizations with your account or tracking ID.</p></div><Link className="btn btn-awareness" to="/organizations">Contact an organization</Link></div><form className="tracking-lookup" onSubmit={(e) => { e.preventDefault(); setTrackingId(lookup.trim()); }}><label htmlFor="tracking">Tracking ID</label><input id="tracking" value={lookup} onChange={(e) => setLookup(e.target.value)} placeholder="Example: DS-4A8F21C0" /><button className="btn btn-outline-ink">Find request</button>{user && <span>Signed in as {user.name}; your account requests are loaded automatically.</span>}</form>{error && <div className="error-banner">{error}</div>}<section className="request-workspace"><div className="request-list">{requests.length === 0 ? <div className="empty-state"><h2>No requests found</h2><p>Submit a request or enter its tracking ID above.</p></div> : requests.map((request) => <button className={`request-row ${selected?.id === request.id ? "selected" : ""}`} key={request.id} onClick={() => setSelected(request)}><span className={`urgency-dot ${urgencyClass(request.urgency)}`} /><span className="request-row-copy"><strong>{request.organization_name}</strong><small>{request.category} · {request.tracking_id}</small></span><span className={`status-pill status-${request.status.toLowerCase().replace(" ", "-")}`}>{request.status}</span></button>)}</div><div className="thread-panel">{selected ? <><div className="thread-header"><div><p className="eyebrow">{selected.tracking_id}</p><h2>{selected.organization_name}</h2><span className={`urgency-badge ${urgencyClass(selected.urgency)}`}>{selected.urgency} urgency · {selected.category}</span></div><span className={`status-pill status-${selected.status.toLowerCase().replace(" ", "-")}`}>{selected.status}</span></div><div className="message-stream">{selected.messages?.map((item) => <div className={`message-bubble ${item.sender_role === "citizen" ? "from-citizen" : "from-org"}`} key={item.id}><small>{item.sender_role === "citizen" ? "You" : selected.organization_name}</small><p>{item.body}</p><time>{new Date(item.created_at).toLocaleString()}</time></div>)}</div><form className="reply-box" onSubmit={send}><textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Continue the conversation…" rows="3" /><button className="btn btn-awareness">Send message</button></form></> : <div className="empty-state"><span className="aside-icon">✦</span><h2>Select a request</h2><p>Your conversation will appear here.</p></div>}</div></section></main>;
}
