import React, { useEffect, useState } from "react";
import { api } from "../../services/api";

const URGENCY_LABELS = { critical: "Critical", medium: "Medium", low: "Low" };
const urgencyClass = (urgency) => urgency === "critical" ? "urgency-pill urgency-critical" : urgency === "medium" ? "urgency-pill urgency-medium" : "urgency-pill urgency-low";

export default function AdminAssistanceList() {
  const [requests, setRequests] = useState([]); const [organizations, setOrganizations] = useState([]); const [filters, setFilters] = useState({ urgency: "", status: "", sort: "urgency" }); const [error, setError] = useState("");
  async function load() { try { const [requestResponse, orgResponse] = await Promise.all([api.get("/help-requests", { params: filters }), api.get("/organizations/admin/all")]); setRequests(requestResponse.data.requests || []); setOrganizations((orgResponse.data.organizations || []).filter((org) => org.verification_status === "Verified")); } catch { setError("Could not load help requests."); } }
  useEffect(() => { load(); }, [filters.urgency, filters.status, filters.sort]);
  async function update(id, changes) { try { const { data } = await api.patch(`/help-requests/${id}`, changes); setRequests((items) => items.map((item) => item.id === id ? { ...item, ...data.request } : item)); } catch { setError("Could not update help request."); } }
  return <div className="admin-page"><div className="admin-heading-row"><div><h1>Help Requests</h1><p className="dashboard-muted">Triage public requests and assign them to a response organization.</p></div><div className="admin-filter-row"><select value={filters.urgency} onChange={(e) => setFilters({ ...filters, urgency: e.target.value })}><option value="">All urgency</option><option value="critical">Critical</option><option value="medium">Medium</option><option value="low">Low</option></select><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">All status</option><option value="new">New</option><option value="in_review">In review</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><select value={filters.sort} onChange={(e) => setFilters({ ...filters, sort: e.target.value })}><option value="urgency">Sort: urgency</option><option value="date">Sort: newest</option></select></div></div>{error && <div className="error-banner">{error}</div>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Request</th><th>Need</th><th>Location</th><th>Urgency</th><th>Status</th><th>Assign to</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id}><td><strong>#{request.request_id}</strong><br />{request.name}<br /><small>{request.phone || request.email}</small></td><td>{request.type}</td><td>{request.location_text || `${request.latitude}, ${request.longitude}`}<br /><small>{request.description}</small></td><td><span className={urgencyClass(request.urgency)}>{URGENCY_LABELS[request.urgency]}</span></td><td><select value={request.status} onChange={(e) => update(request.id, { status: e.target.value, assignedTo: request.assigned_to })}><option value="new">New</option><option value="in_review">In review</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></td><td><select value={request.assigned_to || ""} onChange={(e) => update(request.id, { assignedTo: e.target.value || null, status: request.status })}><option value="">Unassigned</option>{organizations.map((org) => <option key={org.id} value={org.user_id}>{org.name}</option>)}</select></td></tr>)}</tbody></table></div></div>;
}
